import "server-only";
import { promises as fs } from "node:fs";
import path from "node:path";
import { env } from "./env";

/**
 * Tiny key/value + binary store. Netlify Blobs in production, ./.data on disk
 * for local development. Keys look like "cms/settings" or "media/abc123".
 */
export interface BlobMeta {
  [k: string]: string | number | boolean;
}

interface Driver {
  getJSON<T>(key: string): Promise<T | null>;
  setJSON(key: string, value: unknown): Promise<void>;
  getBinary(key: string): Promise<{ data: ArrayBuffer; meta: BlobMeta } | null>;
  setBinary(key: string, data: ArrayBuffer, meta: BlobMeta): Promise<void>;
  list(prefix: string): Promise<string[]>;
  delete(key: string): Promise<void>;
}

const STORE_NAME = "sinvesta-cms";

function netlifyDriver(): Driver {
  // Imported lazily so local dev never needs the Netlify runtime.
  const storeP = import("@netlify/blobs").then(({ getStore }) =>
    getStore({ name: STORE_NAME, consistency: "strong" }),
  );
  return {
    async getJSON<T>(key: string) {
      return ((await (await storeP).get(key, { type: "json" })) as T) ?? null;
    },
    async setJSON(key, value) {
      await (await storeP).setJSON(key, value);
    },
    async getBinary(key) {
      const r = await (await storeP).getWithMetadata(key, { type: "arrayBuffer" });
      return r ? { data: r.data, meta: r.metadata as BlobMeta } : null;
    },
    async setBinary(key, data, meta) {
      await (await storeP).set(key, data, { metadata: meta });
    },
    async list(prefix) {
      const { blobs } = await (await storeP).list({ prefix });
      return blobs.map((b) => b.key);
    },
    async delete(key) {
      await (await storeP).delete(key);
    },
  };
}

function fileDriver(): Driver {
  const root = path.join(process.cwd(), ".data");
  // Keys are generated by us, but never let one climb out of the data folder.
  const resolve = (key: string, ext: string) => {
    if (!/^[a-z0-9/_.-]+$/i.test(key) || key.includes("..")) throw new Error("Bad store key");
    return path.join(root, key + ext);
  };
  const readOrNull = async (p: string) => fs.readFile(p).catch(() => null);
  const write = async (p: string, data: string | Uint8Array) => {
    await fs.mkdir(path.dirname(p), { recursive: true });
    await fs.writeFile(p, data);
  };
  return {
    async getJSON<T>(key: string) {
      const buf = await readOrNull(resolve(key, ".json"));
      return buf ? (JSON.parse(buf.toString("utf8")) as T) : null;
    },
    async setJSON(key, value) {
      await write(resolve(key, ".json"), JSON.stringify(value, null, 2));
    },
    async getBinary(key) {
      const [data, meta] = await Promise.all([
        readOrNull(resolve(key, ".bin")),
        readOrNull(resolve(key, ".meta.json")),
      ]);
      if (!data) return null;
      const ab = data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) as ArrayBuffer;
      return { data: ab, meta: meta ? JSON.parse(meta.toString("utf8")) : {} };
    },
    async setBinary(key, data, meta) {
      await write(resolve(key, ".bin"), new Uint8Array(data));
      await write(resolve(key, ".meta.json"), JSON.stringify(meta));
    },
    async list(prefix) {
      const dir = path.join(root, prefix.replace(/\/[^/]*$/, ""));
      const files = await fs.readdir(dir).catch(() => [] as string[]);
      const base = prefix.slice(0, prefix.lastIndexOf("/") + 1);
      const keys = new Set<string>();
      for (const f of files) {
        const k = base + f.replace(/\.(meta\.json|json|bin)$/, "");
        if (k.startsWith(prefix)) keys.add(k);
      }
      return [...keys];
    },
    async delete(key) {
      await Promise.all(
        [".json", ".bin", ".meta.json"].map((ext) => fs.rm(resolve(key, ext), { force: true })),
      );
    },
  };
}

let driver: Driver | null = null;
export function store(): Driver {
  driver ??= env.storage === "netlify" ? netlifyDriver() : fileDriver();
  return driver;
}
