import type { Config } from "@netlify/edge-functions";
import { getText } from "./lib/config.ts";

/**
 * /sitemap.xml and /robots.txt, generated by the admin's Sitemap & Robots
 * page. If the admin can't be reached, a safe built-in version is served so
 * crawlers never see an error.
 */
const SITE = "https://www.sinvesta.com.au";
const PAGES = ["/", "/packages.html", "/rebates.html", "/projects.html", "/about.html", "/contact.html"];

const FALLBACK = {
  "/sitemap.xml": `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${PAGES.map((p) => `  <url><loc>${SITE}${p}</loc></url>`).join("\n")}\n</urlset>\n`,
  "/robots.txt": `User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /admin/\n\nSitemap: ${SITE}/sitemap.xml\n`,
};
const SOURCE = { "/sitemap.xml": "/admin/api/public/sitemap", "/robots.txt": "/admin/api/public/robots" };
const TYPE = { "/sitemap.xml": "application/xml; charset=utf-8", "/robots.txt": "text/plain; charset=utf-8" };

export default async (request: Request) => {
  const url = new URL(request.url);
  const path = url.pathname as keyof typeof SOURCE;
  let body: string;
  try {
    body = await getText(url.origin, SOURCE[path]);
  } catch (err) {
    console.log(`[seo-files] ${path} fallback:`, String(err));
    body = FALLBACK[path];
  }
  return new Response(body, { headers: { "content-type": TYPE[path], "cache-control": "public, max-age=300" } });
};

export const config: Config = { path: ["/sitemap.xml", "/robots.txt"] };
